'use client'
import { useState, useEffect } from 'react'
import Link from 'next/link'
import { useLanguage, Language } from '@/lib/LanguageContext'
import { useToast } from '@/components/Toast'
import { supabase } from '@/lib/supabase'

const texts: Record<Language, any> = {
  en: { back: '← Back', title: 'Text to Speech', subtitle: 'Convert your text into natural-sounding voice', credits: '3 Credits', inputLabel: 'Enter text to convert', inputPlaceholder: 'Type the text you want to convert to speech...', voiceLabel: 'Voice', voices: { male: 'Male', female: 'Female' }, generate: 'Generate Audio', generating: 'Converting...', result: 'Audio', play: 'Play', download: 'Download', emptyInput: 'Please enter some text', success: 'Audio generated!', error: 'Error occurred' },
  tr: { back: '← Geri', title: 'Seslendirme', subtitle: 'Metinlerinizi doğal sese dönüştürün', credits: '3 Kredi', inputLabel: 'Dönüştürülecek metni girin', inputPlaceholder: 'Sese dönüştürmek istediğiniz metni yazın...', voiceLabel: 'Ses', voices: { male: 'Erkek', female: 'Kadın' }, generate: 'Ses Oluştur', generating: 'Dönüştürülüyor...', result: 'Ses', play: 'Oynat', download: 'İndir', emptyInput: 'Lütfen metin girin', success: 'Ses oluşturuldu!', error: 'Hata oluştu' },
  ru: { back: '← Назад', title: 'Озвучка текста', subtitle: 'Преобразуйте текст в естественную речь', credits: '3 кредита', inputLabel: 'Введите текст', inputPlaceholder: 'Введите текст для озвучки...', voiceLabel: 'Голос', voices: { male: 'Мужской', female: 'Женский' }, generate: 'Создать аудио', generating: 'Преобразование...', result: 'Аудио', play: 'Воспроизвести', download: 'Скачать', emptyInput: 'Введите текст', success: 'Аудио создано!', error: 'Ошибка' },
  de: { back: '← Zurück', title: 'Text zu Sprache', subtitle: 'Wandeln Sie Text in natürliche Sprache um', credits: '3 Credits', inputLabel: 'Text eingeben', inputPlaceholder: 'Geben Sie den Text ein...', voiceLabel: 'Stimme', voices: { male: 'Männlich', female: 'Weiblich' }, generate: 'Audio erstellen', generating: 'Konvertierung...', result: 'Audio', play: 'Abspielen', download: 'Herunterladen', emptyInput: 'Bitte Text eingeben', success: 'Audio erstellt!', error: 'Fehler' },
  fr: { back: '← Retour', title: 'Synthèse vocale', subtitle: 'Convertissez le texte en voix naturelle', credits: '3 Crédits', inputLabel: 'Entrez le texte', inputPlaceholder: 'Tapez le texte à convertir...', voiceLabel: 'Voix', voices: { male: 'Masculine', female: 'Féminine' }, generate: 'Générer l\'audio', generating: 'Conversion...', result: 'Audio', play: 'Lecture', download: 'Télécharger', emptyInput: 'Veuillez entrer du texte', success: 'Audio créé!', error: 'Erreur' }
}
const langs: { code: Language; flag: string }[] = [{ code: 'en', flag: '🇺🇸' }, { code: 'tr', flag: '🇹🇷' }, { code: 'ru', flag: '🇷🇺' }, { code: 'de', flag: '🇩🇪' }, { code: 'fr', flag: '🇫🇷' }]

export default function TextToSpeechPage() {
  const [input, setInput] = useState(''); const [voice, setVoice] = useState('female'); const [audioUrl, setAudioUrl] = useState(''); const [loading, setLoading] = useState(false); const [userId, setUserId] = useState<string | null>(null)
  const { language, setLanguage } = useLanguage(); const { showToast } = useToast(); const t = texts[language]
  useEffect(() => { supabase.auth.getUser().then(({ data: { user } }) => { if (user) setUserId(user.id) }) }, [])
  const handleGenerate = async () => { if (!input.trim()) { showToast(t.emptyInput, 'warning'); return }; setLoading(true); setAudioUrl(''); try { const response = await fetch('/api/text-to-speech', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ input, voice, userId, language }) }); const data = await response.json(); if (data.error) { showToast(data.error, 'error') } else { setAudioUrl(data.audioUrl || ''); showToast(t.success, 'success') } } catch (err) { showToast(t.error, 'error') }; setLoading(false) }
  return (
    <div className="min-h-screen bg-gray-900 text-white">
      <header className="bg-gray-800/50 backdrop-blur-xl border-b border-gray-700/50 sticky top-0 z-50"><div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between"><Link href="/dashboard" className="text-gray-400 hover:text-white transition">{t.back}</Link><div className="flex items-center gap-3"><div className="flex bg-gray-800 rounded-xl p-1 border border-gray-700">{langs.map((l) => (<button key={l.code} onClick={() => setLanguage(l.code)} className={`px-2.5 py-1.5 rounded-lg text-sm transition ${language === l.code ? 'bg-purple-600 text-white' : 'text-gray-400 hover:text-white'}`}>{l.flag}</button>))}</div><span className="text-2xl">🔊</span></div></div></header>
      <main className="max-w-4xl mx-auto px-4 py-8">
        <div className="text-center mb-8"><div className="inline-flex items-center gap-2 bg-purple-500/20 text-purple-400 px-4 py-2 rounded-full text-sm font-medium mb-4"><span>⚡</span><span>{t.credits}</span></div><div className="text-5xl mb-4">🔊</div><h1 className="text-3xl sm:text-4xl font-bold mb-2">{t.title}</h1><p className="text-gray-400">{t.subtitle}</p></div>
        <div className="bg-gray-800/50 rounded-2xl border border-gray-700 p-6 mb-6 space-y-5"><div><label className="block text-sm font-medium text-gray-300 mb-2">{t.inputLabel}</label><textarea value={input} onChange={(e) => setInput(e.target.value)} placeholder={t.inputPlaceholder} className="w-full h-40 px-4 py-3 bg-gray-900/50 border border-gray-700 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-purple-500 resize-none" /></div><div><label className="block text-sm font-medium text-gray-300 mb-2">{t.voiceLabel}</label><select value={voice} onChange={(e) => setVoice(e.target.value)} className="w-full px-4 py-3 bg-gray-900/50 border border-gray-700 rounded-xl text-white">{Object.entries(t.voices).map(([k, v]) => (<option key={k} value={k}>{v as string}</option>))}</select></div></div>
        <button onClick={handleGenerate} disabled={loading} className="w-full bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 disabled:opacity-50 py-4 rounded-xl font-semibold text-lg transition flex items-center justify-center gap-3 mb-8">{loading ? (<><span className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></span>{t.generating}</>) : (<><span>🔊</span>{t.generate}</>)}</button>
        {audioUrl && (<div className="bg-gray-800/50 rounded-2xl border border-gray-700 p-6 text-center"><h2 className="text-xl font-semibold mb-4">{t.result}</h2><audio controls src={audioUrl} className="w-full mb-4" /><a href={audioUrl} download className="inline-flex items-center gap-2 px-6 py-3 bg-purple-600 hover:bg-purple-700 rounded-xl font-medium transition"><span>⬇️</span>{t.download}</a></div>)}
      </main>
    </div>
  )
}
