// Export utilities for content library
// Supports Markdown and plain text export

export function resultToMarkdown(toolName: string, inputSummary: string, result: any, date: string): string {
  const title = toolName.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())
  let md = `# ${title}\n\n`
  md += `**Input:** ${inputSummary}\n`
  md += `**Date:** ${new Date(date).toLocaleDateString()}\n\n---\n\n`

  // Hook Generator
  if (result.hooks) {
    if (result.best_hook) md += `## 🏆 Best Hook\n\n${result.best_hook.text}\n\n> ${result.best_hook.reason || ''}\n\n`
    md += `## All Hooks\n\n`
    result.hooks.forEach((h: any, i: number) => {
      md += `${i + 1}. **${h.text}**\n`
      if (h.pattern) md += `   - Pattern: ${h.pattern}`
      if (h.virality_score) md += ` | Virality: ${h.virality_score}/10`
      md += `\n`
      if (h.why_it_works) md += `   - ${h.why_it_works}\n`
      md += `\n`
    })
    if (result.topic_insight) md += `## 💡 Topic Insight\n\n${result.topic_insight}\n\n`
  }

  // Caption Generator
  else if (result.captions) {
    if (result.best_caption) md += `## 🏆 Best Caption\n\n${result.best_caption.text}\n\n`
    md += `## All Captions\n\n`
    result.captions.forEach((c: any, i: number) => {
      md += `### Caption ${i + 1}\n\n${c.text || c.caption}\n\n`
      if (c.style) md += `*Style: ${c.style}*\n\n`
    })
    if (result.hashtags) md += `## #️⃣ Hashtags\n\n${result.hashtags.join(' ')}\n\n`
  }

  // Script Studio
  else if (result.script) {
    if (result.script.full_script) md += `## 📝 Full Script\n\n${result.script.full_script}\n\n`
    if (result.scene_breakdown) {
      md += `## 🎬 Scene Breakdown\n\n`
      result.scene_breakdown.forEach((s: any) => {
        md += `**Scene ${s.scene}: ${s.section}** (${s.duration})\n\n${s.text}\n\n`
      })
    }
    if (result.title_options) md += `## 📌 Title Options\n\n${result.title_options.map((t: string, i: number) => `${i + 1}. ${t}`).join('\n')}\n\n`
    if (result.hashtags) md += `## #️⃣ Hashtags\n\n${result.hashtags.join(' ')}\n\n`
  }

  // Viral Analyzer
  else if (result.final_score !== undefined) {
    md += `## 📊 Viral Score: ${result.final_score}/100\n\n`
    if (result.verdict) md += `**Verdict:** ${result.verdict}\n\n`
    if (result.strengths) md += `### ✅ Strengths\n\n${result.strengths.map((s: string) => `- ${s}`).join('\n')}\n\n`
    if (result.weaknesses) md += `### ⚠️ Weaknesses\n\n${result.weaknesses.map((w: string) => `- ${w}`).join('\n')}\n\n`
    if (result.rewritten_hook) md += `### 🎯 Suggested Hook\n\n${result.rewritten_hook}\n\n`
  }

  // Thread Composer
  else if (result.tweets) {
    md += `## 🧵 Thread\n\n`
    result.tweets.forEach((t: any, i: number) => {
      md += `**Tweet ${t.number || i + 1}** ${t.type ? `(${t.type})` : ''}\n\n${t.text}\n\n---\n\n`
    })
  }

  // Content Planner
  else if (result.calendar) {
    md += `## 📅 Content Calendar\n\n`
    if (result.content_pillars) md += `**Content Pillars:** ${result.content_pillars.join(', ')}\n\n`
    result.calendar.forEach((week: any) => {
      md += `### Week ${week.week}\n\n`
      week.days?.forEach((day: any) => {
        md += `**${day.day}**\n\n`
        day.posts?.forEach((post: any) => {
          md += `- ${post.platform}: ${post.topic}\n  - Hook: ${post.hook || '-'}\n  - Time: ${post.best_time || '-'}\n\n`
        })
      })
    })
  }

  // Competitor Spy
  else if (result.competitor_analysis) {
    md += `## 🕵️ Competitor Analysis\n\n`
    md += `**Strategy:** ${result.competitor_analysis.content_strategy || '-'}\n\n`
    if (result.opportunities) {
      md += `### 🚀 Opportunities\n\n`
      result.opportunities.forEach((o: any) => md += `- **${o.gap}** → ${o.your_angle} *(${o.priority})*\n`)
      md += `\n`
    }
    if (result.action_plan) md += `### 🎯 Action Plan\n\n${result.action_plan.map((a: string, i: number) => `${i + 1}. ${a}`).join('\n')}\n\n`
  }

  // A/B Tester
  else if (result.winner) {
    md += `## 🏆 Winner: Version ${result.winner}\n\n`
    if (result.recommendation) md += `**Recommendation:** ${result.recommendation}\n\n`
    if (result.improved_version) md += `### ✨ Improved Version\n\n${result.improved_version}\n\n`
  }

  // Carousel Planner
  else if (result.carousel) {
    md += `## 🎠 ${result.carousel.title || 'Carousel'}\n\n`
    result.carousel.slides?.forEach((s: any) => {
      md += `**Slide ${s.slide_number}: ${s.headline}**\n\n${s.subtext || ''}\n\n`
    })
    if (result.carousel.caption) md += `### ✍️ Caption\n\n${result.carousel.caption}\n\n`
  }

  // Generic fallback
  else if (result.raw) {
    md += result.raw + '\n\n'
  } else {
    md += '```json\n' + JSON.stringify(result, null, 2) + '\n```\n\n'
  }

  md += `---\n\n*Generated by [MediaToolkit](https://mediatoolkit.site)*`
  return md
}

export function resultToPlainText(toolName: string, inputSummary: string, result: any): string {
  const title = toolName.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())
  let txt = `${title}\n${'='.repeat(40)}\n\nInput: ${inputSummary}\n\n`

  if (result.hooks) {
    result.hooks.forEach((h: any, i: number) => { txt += `${i + 1}. ${h.text}\n` })
  } else if (result.captions) {
    result.captions.forEach((c: any, i: number) => { txt += `${i + 1}. ${c.text || c.caption}\n\n` })
  } else if (result.script?.full_script) {
    txt += result.script.full_script
  } else if (result.tweets) {
    result.tweets.forEach((t: any) => { txt += `${t.text}\n\n---\n\n` })
  } else if (result.raw) {
    txt += result.raw
  } else {
    txt += JSON.stringify(result, null, 2)
  }

  txt += `\n\n${'='.repeat(40)}\nGenerated by MediaToolkit\nhttps://mediatoolkit.site`
  return txt
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
