'use client'
import { useState, useEffect } from 'react'
import Link from 'next/link'
import { useLanguage, Language } from '@/lib/LanguageContext'
import { useToast } from '@/components/Toast'
import { supabase } from '@/lib/supabase'

const texts: Record<Language, any> = {
  en: { back: '← Back', title: 'Subtitle Generator', subtitle: 'Generate accurate subtitles for your videos', credits: '5 Credits', inputLabel: 'Video transcript or script', inputPlaceholder: 'Paste your video transcript or script here...', formatLabel: 'Format', formats: { srt: 'SRT', vtt: 'VTT', txt: 'Plain Text' }, generate: 'Generate Subtitles', generating: 'Generating...', result: 'Subtitles', copy: 'Copy', copied: 'Copied!', download: 'Download', emptyInput: 'Please enter a transcript', success: 'Subtitles generated!', error: 'Error occurred' },
  tr: { back: '← Geri', title: 'Altyazı Üretici', subtitle: 'Videolarınız için doğru altyazılar oluşturun', credits: '5 Kredi', inputLabel: 'Video transkripti veya scripti', inputPlaceholder: 'Video transkriptinizi veya scriptinizi yapıştırın...', formatLabel: 'Format', formats: { srt: 'SRT', vtt: 'VTT', txt: 'Düz Metin' }, generate: 'Altyazı Oluştur', generating: 'Oluşturuluyor...', result: 'Altyazılar', copy: 'Kopyala', copied: 'Kopyalandı!', download: 'İndir', emptyInput: 'Lütfen transkript girin', success: 'Altyazılar oluşturuldu!', error: 'Hata oluştu' },
  ru: { back: '← Назад', title: 'Генератор субтитров', subtitle: 'Создавайте точные субтитры для видео', credits: '5 кредитов', inputLabel: 'Транскрипт или сценарий', inputPlaceholder: 'Вставьте транскрипт видео...', formatLabel: 'Формат', formats: { srt: 'SRT', vtt: 'VTT', txt: 'Текст' }, generate: 'Создать субтитры', generating: 'Создание...', result: 'Субтитры', copy: 'Копировать', copied: 'Скопировано!', download: 'Скачать', emptyInput: 'Введите транскрипт', success: 'Субтитры созданы!', error: 'Ошибка' },
  de: { back: '← Zurück', title: 'Untertitel-Generator', subtitle: 'Erstellen Sie Untertitel für Ihre Videos', credits: '5 Credits', inputLabel: 'Video-Transkript oder Skript', inputPlaceholder: 'Fügen Sie das Transkript ein...', formatLabel: 'Format', formats: { srt: 'SRT', vtt: 'VTT', txt: 'Text' }, generate: 'Untertitel erstellen', generating: 'Wird erstellt...', result: 'Untertitel', copy: 'Kopieren', copied: 'Kopiert!', download: 'Herunterladen', emptyInput: 'Bitte Transkript eingeben', success: 'Untertitel erstellt!', error: 'Fehler' },
  fr: { back: '← Retour', title: 'Générateur de sous-titres', subtitle: 'Créez des sous-titres précis pour vos vidéos', credits: '5 Crédits', inputLabel: 'Transcription ou script', inputPlaceholder: 'Collez la transcription de votre vidéo...', formatLabel: 'Format', formats: { srt: 'SRT', vtt: 'VTT', txt: 'Texte' }, generate: 'Générer les sous-titres', generating: 'Génération...', result: 'Sous-titres', copy: 'Copier', copied: 'Copié!', download: 'Télécharger', emptyInput: 'Entrez une transcription', success: 'Sous-titres créés!', error: 'Erreur' }
}
const langs: { code: Language; flag: string }[] = [{ code: 'en', flag: '🇺🇸' }, { code: 'tr', flag: '🇹🇷' }, { code: 'ru', flag: '🇷🇺' }, { code: 'de', flag: '🇩🇪' }, { code: 'fr', flag: '🇫🇷' }]

export default function SubtitleGeneratorPage() {
  const [input, setInput] = useState(''); const [format, setFormat] = useState('srt'); const [result, setResult] = useState(''); const [loading, setLoading] = useState(false); const [userId, setUserId] = useState<string | null>(null); const [copied, setCopied] = useState(false)
  const { language, setLanguage } = useLanguage(); const { showToast } = useToast(); const t = texts[language]
  useEffect(() => { supabase.auth.getUser().then(({ data: { user } }) => { if (user) setUserId(user.id) }) }, [])
  const handleGenerate = async () => { if (!input.trim()) { showToast(t.emptyInput, 'warning'); return }; setLoading(true); setResult(''); try { const response = await fetch('/api/subtitle-generator', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ input, format, userId, language }) }); const data = await response.json(); if (data.error) { showToast(data.error, 'error') } else { setResult(data.subtitles || JSON.stringify(data)); showToast(t.success, 'success') } } catch (err) { showToast(t.error, 'error') }; setLoading(false) }
  const handleCopy = () => { navigator.clipboard.writeText(result); setCopied(true); showToast(t.copied, 'success'); setTimeout(() => setCopied(false), 2000) }
  return (
    <div className="min-h-screen bg-gray-900 text-white">
      <header className="bg-gray-800/50 backdrop-blur-xl border-b border-gray-700/50 sticky top-0 z-50"><div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between"><Link href="/dashboard" className="text-gray-400 hover:text-white transition">{t.back}</Link><div className="flex items-center gap-3"><div className="flex bg-gray-800 rounded-xl p-1 border border-gray-700">{langs.map((l) => (<button key={l.code} onClick={() => setLanguage(l.code)} className={`px-2.5 py-1.5 rounded-lg text-sm transition ${language === l.code ? 'bg-purple-600 text-white' : 'text-gray-400 hover:text-white'}`}>{l.flag}</button>))}</div><span className="text-2xl">📺</span></div></div></header>
      <main className="max-w-4xl mx-auto px-4 py-8">
        <div className="text-center mb-8"><div className="inline-flex items-center gap-2 bg-purple-500/20 text-purple-400 px-4 py-2 rounded-full text-sm font-medium mb-4"><span>⚡</span><span>{t.credits}</span></div><div className="text-5xl mb-4">📺</div><h1 className="text-3xl sm:text-4xl font-bold mb-2">{t.title}</h1><p className="text-gray-400">{t.subtitle}</p></div>
        <div className="bg-gray-800/50 rounded-2xl border border-gray-700 p-6 mb-6 space-y-5"><div><label className="block text-sm font-medium text-gray-300 mb-2">{t.inputLabel}</label><textarea value={input} onChange={(e) => setInput(e.target.value)} placeholder={t.inputPlaceholder} className="w-full h-48 px-4 py-3 bg-gray-900/50 border border-gray-700 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-purple-500 resize-none" /></div><div><label className="block text-sm font-medium text-gray-300 mb-2">{t.formatLabel}</label><select value={format} onChange={(e) => setFormat(e.target.value)} className="w-full px-4 py-3 bg-gray-900/50 border border-gray-700 rounded-xl text-white">{Object.entries(t.formats).map(([k, v]) => (<option key={k} value={k}>{v as string}</option>))}</select></div></div>
        <button onClick={handleGenerate} disabled={loading} className="w-full bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 disabled:opacity-50 py-4 rounded-xl font-semibold text-lg transition flex items-center justify-center gap-3 mb-8">{loading ? (<><span className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></span>{t.generating}</>) : (<><span>📺</span>{t.generate}</>)}</button>
        {result && (<div className="bg-gray-800/50 rounded-2xl border border-gray-700 p-6"><div className="flex items-center justify-between mb-4"><h2 className="text-xl font-semibold">{t.result}</h2><button onClick={handleCopy} className={`px-4 py-2 rounded-xl text-sm font-medium transition ${copied ? 'bg-green-600' : 'bg-gray-700 hover:bg-gray-600'}`}>{copied ? t.copied : t.copy}</button></div><div className="bg-gray-900/50 rounded-xl p-5 border border-gray-700"><pre className="text-gray-300 whitespace-pre-wrap leading-relaxed text-sm font-mono">{result}</pre></div></div>)}
      </main>
    </div>
  )
}
