'use client'
import { useState } from 'react'
import Link from 'next/link'
import { useLanguage, Language } from '@/lib/LanguageContext'
import { useToast } from '@/components/Toast'
const texts: Record<Language, any> = {
  en: { back: '← Back to Dashboard', title: 'Subtitle Generator', subtitle: 'Generate subtitles for videos', credits: '5 Credits', text: 'Video Script', placeholder: 'Paste your script...', targetLang: 'Target Language', format: 'Format', generate: 'Generate Subtitles', generating: 'Generating...', result: 'Generated Subtitles', copy: 'Copy', download: 'Download', copied: 'Copied!', required: 'Text required', success: 'Done!', error: 'Error', languages: { en: 'English', tr: 'Turkish', es: 'Spanish', fr: 'French', de: 'German' }, formats: { srt: 'SRT', vtt: 'VTT', txt: 'TXT' } },
  tr: { back: '← Panele Dön', title: 'Altyazı Üretici', subtitle: 'Videolar için altyazı oluştur', credits: '5 Kredi', text: 'Video Scripti', placeholder: 'Scriptinizi yapıştırın...', targetLang: 'Hedef Dil', format: 'Format', generate: 'Altyazı Oluştur', generating: 'Oluşturuluyor...', result: 'Oluşturulan Altyazı', copy: 'Kopyala', download: 'İndir', copied: 'Kopyalandı!', required: 'Metin gerekli', success: 'Tamam!', error: 'Hata', languages: { en: 'İngilizce', tr: 'Türkçe', es: 'İspanyolca', fr: 'Fransızca', de: 'Almanca' }, formats: { srt: 'SRT', vtt: 'VTT', txt: 'TXT' } },
  ru: { back: '← Назад', title: 'Генератор субтитров', subtitle: 'Создайте субтитры', credits: '5 Кредитов', text: 'Сценарий', placeholder: 'Вставьте сценарий...', targetLang: 'Целевой язык', format: 'Формат', generate: 'Создать субтитры', generating: 'Создание...', result: 'Субтитры', copy: 'Копировать', download: 'Скачать', copied: 'Скопировано!', required: 'Текст обязателен', success: 'Готово!', error: 'Ошибка', languages: { en: 'Английский', tr: 'Турецкий', es: 'Испанский', fr: 'Французский', de: 'Немецкий' }, formats: { srt: 'SRT', vtt: 'VTT', txt: 'TXT' } },
  de: { back: '← Zurück', title: 'Untertitel-Generator', subtitle: 'Untertitel für Videos', credits: '5 Credits', text: 'Skript', placeholder: 'Skript einfügen...', targetLang: 'Zielsprache', format: 'Format', generate: 'Untertitel erstellen', generating: 'Erstellen...', result: 'Untertitel', copy: 'Kopieren', download: 'Herunterladen', copied: 'Kopiert!', required: 'Text erforderlich', success: 'Fertig!', error: 'Fehler', languages: { en: 'Englisch', tr: 'Türkisch', es: 'Spanisch', fr: 'Französisch', de: 'Deutsch' }, formats: { srt: 'SRT', vtt: 'VTT', txt: 'TXT' } },
  fr: { back: '← Retour', title: 'Générateur de sous-titres', subtitle: 'Créez des sous-titres', credits: '5 Crédits', text: 'Script', placeholder: 'Collez le script...', targetLang: 'Langue cible', format: 'Format', generate: 'Générer sous-titres', generating: 'Génération...', result: 'Sous-titres', copy: 'Copier', download: 'Télécharger', copied: 'Copié!', required: 'Texte requis', success: 'Terminé!', error: 'Erreur', languages: { en: 'Anglais', tr: 'Turc', es: 'Espagnol', fr: 'Français', de: 'Allemand' }, formats: { srt: 'SRT', vtt: 'VTT', txt: 'TXT' } }
}
const languages: { code: Language; flag: string }[] = [{ code: 'en', flag: '🇺🇸' }, { code: 'tr', flag: '🇹🇷' }, { code: 'ru', flag: '🇷🇺' }, { code: 'de', flag: '🇩🇪' }, { code: 'fr', flag: '🇫🇷' }]
export default function Page() {
  const [text, setText] = useState(''); const [targetLang, setTargetLang] = useState('tr'); const [format, setFormat] = useState('srt'); const [result, setResult] = useState(''); const [loading, setLoading] = useState(false)
  const { language, setLanguage } = useLanguage(); const { showToast } = useToast(); const t = texts[language]
  const handleGenerate = async () => { if (!text) { showToast(t.required, 'warning'); return }; setLoading(true); try { const res = await fetch('/api/subtitle-generator', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text, targetLang, format }) }); const data = await res.json(); if (data.subtitle) { setResult(data.subtitle); showToast(t.success, 'success') } } catch { showToast(t.error, 'error') } setLoading(false) }
  const downloadSubtitle = () => { const blob = new Blob([result], { type: 'text/plain' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'subtitle.' + format; a.click(); URL.revokeObjectURL(url) }
  return (
    <div className="min-h-screen bg-gray-900 text-white">
      <header className="bg-gray-800/50 backdrop-blur-md border-b border-gray-700 sticky top-0 z-50"><div className="max-w-6xl mx-auto px-4 py-4 flex justify-between items-center"><Link href="/dashboard" className="text-gray-400 hover:text-white transition">{t.back}</Link><div className="flex items-center gap-4"><div className="flex items-center bg-gray-800 rounded-lg p-1">{languages.map((lang) => (<button key={lang.code} onClick={() => setLanguage(lang.code)} className={`px-2 py-1 rounded text-xs transition ${language === lang.code ? 'bg-purple-500 text-white' : 'text-gray-400'}`}>{lang.flag}</button>))}</div><span className="text-2xl">📝</span></div></div></header>
      <main className="max-w-4xl mx-auto px-4 py-8">
        <div className="text-center mb-8"><span className="inline-block px-3 py-1 bg-purple-500/20 text-purple-400 text-sm rounded-full mb-4">⚡ {t.credits}</span><h1 className="text-4xl font-bold mb-2">{t.title}</h1><p className="text-gray-400">{t.subtitle}</p></div>
        <div className="bg-gray-800 rounded-2xl p-6 mb-8">
          <div className="mb-4"><label className="block text-sm font-medium mb-2">{t.text}</label><textarea value={text} onChange={(e) => setText(e.target.value)} placeholder={t.placeholder} rows={5} className="w-full px-4 py-3 bg-gray-900 border border-gray-700 rounded-xl resize-none" /></div>
          <div className="grid md:grid-cols-2 gap-4 mb-4">
            <div><label className="block text-sm font-medium mb-2">{t.targetLang}</label><select value={targetLang} onChange={(e) => setTargetLang(e.target.value)} className="w-full px-4 py-3 bg-gray-900 border border-gray-700 rounded-xl">{Object.entries(t.languages).map(([k,v]) => <option key={k} value={k}>{v as string}</option>)}</select></div>
            <div><label className="block text-sm font-medium mb-2">{t.format}</label><select value={format} onChange={(e) => setFormat(e.target.value)} className="w-full px-4 py-3 bg-gray-900 border border-gray-700 rounded-xl">{Object.entries(t.formats).map(([k,v]) => <option key={k} value={k}>{v as string}</option>)}</select></div>
          </div>
          <button onClick={handleGenerate} disabled={loading} className="w-full py-4 bg-gradient-to-r from-purple-600 to-pink-600 rounded-xl font-semibold transition disabled:opacity-50">{loading ? t.generating : t.generate}</button>
        </div>
        {result && (<div className="bg-gray-800 rounded-2xl p-6"><div className="flex justify-between items-center mb-4"><h2 className="text-xl font-semibold">{t.result}</h2><div className="flex gap-2"><button onClick={() => {navigator.clipboard.writeText(result); showToast(t.copied, 'success')}} className="px-4 py-2 bg-gray-700 rounded-lg text-sm">{t.copy}</button><button onClick={downloadSubtitle} className="px-4 py-2 bg-purple-600 rounded-lg text-sm">{t.download}</button></div></div><pre className="text-gray-300 text-sm whitespace-pre-wrap bg-gray-900 p-4 rounded-xl overflow-x-auto">{result}</pre></div>)}
      </main>
    </div>
  )
}
